### ISSUE TITLE
Delete table if the CSV for it starts to 404

### ISSUE THREAD

**Issue by simonw** [simonw/big-local-datasette#11]

**Comment by simonw** [comment]
Maybe just have one run every 24 hours using equivalent of REFRESH_DBS

**Comment by simonw** [comment]
Asked a question about how best to do that: https://github.community/t5/GitHub-Actions/Schedule-once-an-hour-but-do-something-different-once-a-day/m-p/54350#M9148

**Comment by simonw** [comment]
Got a great answer there from @BrightRan:
```yaml
on:
  schedule:
    - cron: '0 1-23 * * *'
    - cron: '0 0 * * *'

jobs:
  test_schedule:
    name: Test schedule
    runs-on: ubuntu-latest
    steps:
      - name: Skip this step every 24 hours
        if: github.event_name == 'schedule' && github.event.schedule != '0 0 * * *'
        run: echo "This step will be skipped every 24 hours"
```
