### ISSUE TITLE
Only pull projects belonging to specific users

### ISSUE THREAD

**Issue by simonw** [simonw/big-local-datasette#14]
For the moment I'm just going to fetch the projects where the contact email is `biglocalnews@stanford.edu`.

**Comment by simonw** [comment]
Oops, I'm still seeing the old projects because we download the previous databases at the start of the action.

**Comment by simonw** [comment]
I'll fix that by temporarily disabling the `datasette-clone` operation. Even better: do that with a conditional:
```
    - name: Download all .db files
      if: !contains(github.event.head_commit.message, 'REFRESH_DBS')
      env:
        DATASETTE_TOKEN: ${{ secrets.DATASETTE_TOKEN }}
      run: |-
        datasette-clone https://biglocal.datasettes.com/ dbs -v --token=$DATASETTE_TOKEN
```
